version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    platform: linux/amd64
    environment:
      SA_PASSWORD: "Bohan233/"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata:
    driver: local